---
source: crates/ruff_linter/src/rules/pygrep_hooks/mod.rs
---
error[PGH005]: PGH005_0.py:2:8: Non-existent mock method: `not_called`

  |
1 | # Errors
2 | assert my_mock.not_called()
  |        ^^^^^^^^^^^^^^^^^^^^
3 | assert my_mock.called_once_with()
4 | assert my_mock.not_called
  |
error[PGH005]: PGH005_0.py:3:8: Non-existent mock method: `called_once_with`

  |
1 | # Errors
2 | assert my_mock.not_called()
3 | assert my_mock.called_once_with()
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^
4 | assert my_mock.not_called
5 | assert my_mock.called_once_with
  |
error[PGH005]: PGH005_0.py:4:8: Non-existent mock method: `not_called`

  |
2 | assert my_mock.not_called()
3 | assert my_mock.called_once_with()
4 | assert my_mock.not_called
  |        ^^^^^^^^^^^^^^^^^^
5 | assert my_mock.called_once_with
6 | my_mock.assert_not_called
  |
error[PGH005]: PGH005_0.py:5:8: Non-existent mock method: `called_once_with`

  |
3 | assert my_mock.called_once_with()
4 | assert my_mock.not_called
5 | assert my_mock.called_once_with
  |        ^^^^^^^^^^^^^^^^^^^^^^^^
6 | my_mock.assert_not_called
7 | my_mock.assert_called
  |
error[PGH005]: PGH005_0.py:6:1: Mock method should be called: `assert_not_called`

  |
4 | assert my_mock.not_called
5 | assert my_mock.called_once_with
6 | my_mock.assert_not_called
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
7 | my_mock.assert_called
8 | my_mock.assert_called_once_with
  |
error[PGH005]: PGH005_0.py:7:1: Mock method should be called: `assert_called`

  |
5 | assert my_mock.called_once_with
6 | my_mock.assert_not_called
7 | my_mock.assert_called
  | ^^^^^^^^^^^^^^^^^^^^^
8 | my_mock.assert_called_once_with
9 | my_mock.assert_called_once_with
  |
error[PGH005]: PGH005_0.py:8:1: Mock method should be called: `assert_called_once_with`

   |
 6 | my_mock.assert_not_called
 7 | my_mock.assert_called
 8 | my_mock.assert_called_once_with
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 9 | my_mock.assert_called_once_with
10 | MyMock.assert_called_once_with
   |
error[PGH005]: PGH005_0.py:9:1: Mock method should be called: `assert_called_once_with`

   |
 7 | my_mock.assert_called
 8 | my_mock.assert_called_once_with
 9 | my_mock.assert_called_once_with
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10 | MyMock.assert_called_once_with
   |
error[PGH005]: PGH005_0.py:10:1: Mock method should be called: `assert_called_once_with`

   |
 8 | my_mock.assert_called_once_with
 9 | my_mock.assert_called_once_with
10 | MyMock.assert_called_once_with
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 | 
12 | # OK
   |
