---
source: crates/ruff_linter/src/rules/pylint/mod.rs
---
error[PLR1704]: redefined_argument_from_local.py:26:9: Redefining argument with the local name `a`

   |
24 | # Errors
25 | def func(a):
26 |     for a in range(1):
   |         ^
27 |         ...
   |
error[PLR1704]: redefined_argument_from_local.py:31:9: Redefining argument with the local name `i`

   |
30 | def func(i):
31 |     for i in range(10):
   |         ^
32 |         print(i)
   |
error[PLR1704]: redefined_argument_from_local.py:38:25: Redefining argument with the local name `e`

   |
36 |     try:
37 |         ...
38 |     except Exception as e:
   |                         ^
39 |         print(e)
   |
error[PLR1704]: redefined_argument_from_local.py:43:24: Redefining argument with the local name `f`

   |
42 | def func(f):
43 |     with open('', ) as f:
   |                        ^
44 |         print(f)
   |
error[PLR1704]: redefined_argument_from_local.py:48:24: Redefining argument with the local name `a`

   |
47 | def func(a, b):
48 |     with context() as (a, b, c):
   |                        ^
49 |         print(a, b, c)
   |
error[PLR1704]: redefined_argument_from_local.py:48:27: Redefining argument with the local name `b`

   |
47 | def func(a, b):
48 |     with context() as (a, b, c):
   |                           ^
49 |         print(a, b, c)
   |
error[PLR1704]: redefined_argument_from_local.py:53:24: Redefining argument with the local name `a`

   |
52 | def func(a, b):
53 |     with context() as [a, b, c]:
   |                        ^
54 |         print(a, b, c)
   |
error[PLR1704]: redefined_argument_from_local.py:53:27: Redefining argument with the local name `b`

   |
52 | def func(a, b):
53 |     with context() as [a, b, c]:
   |                           ^
54 |         print(a, b, c)
   |
error[PLR1704]: redefined_argument_from_local.py:58:51: Redefining argument with the local name `a`

   |
57 | def func(a):
58 |     with open('foo.py', ) as f, open('bar.py') as a:
   |                                                   ^
59 |         ...
   |
error[PLR1704]: redefined_argument_from_local.py:64:13: Redefining argument with the local name `a`

   |
62 | def func(a):
63 |     def bar(b):
64 |         for a in range(1):
   |             ^
65 |             print(a)
   |
error[PLR1704]: redefined_argument_from_local.py:70:13: Redefining argument with the local name `b`

   |
68 | def func(a):
69 |     def bar(b):
70 |         for b in range(1):
   |             ^
71 |             print(b)
   |
error[PLR1704]: redefined_argument_from_local.py:76:13: Redefining argument with the local name `a`

   |
74 | def func(a=1):
75 |     def bar(b=2):
76 |         for a in range(1):
   |             ^
77 |             print(a)
78 |         for b in range(1):
   |
error[PLR1704]: redefined_argument_from_local.py:78:13: Redefining argument with the local name `b`

   |
76 |         for a in range(1):
77 |             print(a)
78 |         for b in range(1):
   |             ^
79 |             print(b)
   |
